sudo: required
dist: trusty

install:
  - 'sudo apt-get update -qq'
  - 'sudo DEBIAN_FRONTEND=noninteractive apt-get install librevenge-dev libvisio-dev libxml2-dev lsb-base libattr1 -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"  -f -q -y || true'

addons_shortcuts:
  addons_clang38: &clang39
    apt:
      sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-trusty' ]
      packages:
        - clang-3.9
        - libboost-dev
        - libxml2-dev
        - valgrind
        - cmake
        - libcppunit-dev
        - autotools-dev
        - doxygen
        - gperf
        - libicu-dev
        - zlib1g-dev
  addons_gcc5: &gcc5
    apt:
      sources: [ 'ubuntu-toolchain-r-test' ]
      packages: 
        - g++-5 
        - gcc-5
        - libboost-dev
        - libxml2-dev
        - valgrind
        - cmake
        - libcppunit-dev
        - autotools-dev
        - doxygen
        - gperf
        - libicu-dev
        - zlib1g-dev

matrix:
  include:
    - os: linux
      compiler: "clang-3.9"
      env: CXX=clang++-3.9 CC=clang-3.9
      addons: *clang39
    - os: linux
      compiler: "gcc-5"
      env: CXX=g++-5 CC=gcc-5
      addons: *gcc5

script: cmake . && make #&& ./tests/resources/check_correctness.sh
