sudo: required
dist: trusty
language: cpp
compiler: clang

install:
  - ./tests/travis-setup.sh 

addons_shortcuts:
  addons_gcc5: &gcc5
    apt:
      sources: [ 'ubuntu-toolchain-r-test', 'ppa:kubuntu-ppa/backports' ]
      packages: 
        - libvisio-dev
        - g++-5 
        - gcc-5
        - libboost-dev
        - libxml2-dev
        - valgrind
        - cmake
        - libcppunit-dev
        - autotools-dev
        - doxygen
        - gperf
        - libicu-dev
        - zlib1g-dev
        - libpng-dev
        - libwmf-dev

matrix:
  include:
    - os: linux
      compiler: "gcc-5"
      env: CXX=g++-5 CC=gcc-5
      addons: *gcc5

script: cmake . -DCMAKE_LIBRARY_PATH=./tests/usr/local/lib/ -DCMAKE_INCLUDE_PATH=./tests/usr/local/include/ -DUSE_CLANG=ON && make #&& ./tests/resources/check_correctness.sh
