sudo: required
dist: trusty

install:
  - 'sudo apt-get update -qq'
  - 'sudo DEBIAN_FRONTEND=noninteractive apt-get install librevenge-dev libvisio-dev libxml2-dev lsb-base libattr1 -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"  -f -q -y || true'

addons_shortcuts:
  addons_clang: &clang
    apt:
            sources: [ 'ubuntu-toolchain-r-test', 'ppa:kubuntu-ppa/backports' ]
      packages:
        - librevenge-dev
        - libvisio-dev
        - clang
        - libboost-dev
        - libxml2-dev
        - valgrind
        - cmake
        - libcppunit-dev
        - autotools-dev
        - doxygen
        - gperf
        - libicu-dev
        - zlib1g-dev
  addons_gcc5: &gcc5
    apt:
            sources: [ 'ubuntu-toolchain-r-test', 'ppa:kubuntu-ppa/backports' ]
      packages: 
        - librevenge-dev
        - libvisio-dev
        - g++-5 
        - gcc-5
        - libboost-dev
        - libxml2-dev
        - valgrind
        - cmake
        - libcppunit-dev
        - autotools-dev
        - doxygen
        - gperf
        - libicu-dev
        - zlib1g-dev

  addons_gcc6: &gcc6
    apt:
            sources: [ 'ubuntu-toolchain-r-test', 'ppa:kubuntu-ppa/backports' ]
      packages: 
        - librevenge-dev
        - libvisio-dev
        - g++-6 
        - gcc-6
        - libboost-dev
        - libxml2-dev
        - valgrind
        - cmake
        - libcppunit-dev
        - autotools-dev
        - doxygen
        - gperf
        - libicu-dev
        - zlib1g-dev

matrix:
  include:
    - os: linux
      compiler: "clang"
      env: CXX=clang++ CC=clang
      addons: *clang
    - os: linux
      compiler: "gcc-5"
      env: CXX=g++-5 CC=gcc-5
      addons: *gcc5
    - os: linux
      compiler: "gcc-6"
      env: CXX=g++-6 CC=gcc-6
      addons: *gcc6

script: cmake . && make #&& ./tests/resources/check_correctness.sh
