sudo: required

install:
  - ./tests/travis-setup.sh 

addons_shortcuts:
  addons_clang: &clang
    apt:
      sources: [ 'ubuntu-toolchain-r-test', 'ppa:kubuntu-ppa/backports' ]
      packages: 
        - libvisio-dev
        - clang
        - libboost-dev
        - libxml2-dev
        - valgrind
        - cmake
        - libcppunit-dev
        - autotools-dev
        - doxygen
        - gperf
        - libicu-dev
        - zlib1g-dev
        - libpng-dev
        - libwmf-dev

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then xcode-select --install;true; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update  ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install argp-standalone; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libwmf; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install valgrind; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libxml2; fi

matrix:
  include:
    - os: linux
      compiler: "clang"
      addons: *clang
      dist: trusty
    - os: osx

script: CC=clang CXX=clang++ cmake . -DCMAKE_LIBRARY_PATH=./tests/usr/local/lib/ -DCMAKE_INCLUDE_PATH=./tests/usr/local/include/ -DUSE_CLANG=ON -DUNSAFE_FILENAME=ON && make #&& ./tests/resources/check_correctness.sh -rsxn
